language: php
sudo: false
dist: trusty

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4

env:
    global:
        - TEST_COMMAND="./vendor/bin/phpunit"

matrix:
    fast_finish: true

    include:
        - php: 7.2
        - php: 7.3
        - php: 7.4

before_install:
    - travis_retry composer self-update

install:
    - COMPOSER_MEMORY_LIMIT=-1 composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
    - $TEST_COMMAND

after_success:
    - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
